import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const baseMigration = await readFile(new URL("../migrations/20260903000600_phase_6_sequence_configuration_drafts.sql", import.meta.url), "utf8");
const migration = await readFile(new URL("../migrations/20260909000100_phase_6_sequence_direct_variants.sql", import.meta.url), "utf8");
const throttleRemovalMigration = await readFile(new URL("../migrations/20260909000200_phase_6_remove_sequence_throttle.sql", import.meta.url), "utf8");
const finalPhaseMigration = await readFile(new URL("../migrations/20260909000300_phase_6_final_sequence_configuration.sql", import.meta.url), "utf8");
const variantRpcRepairMigration = await readFile(new URL("../migrations/20260909000400_phase_6_variant_rpc_signature_repair.sql", import.meta.url), "utf8");
const sequenceData = await readFile(new URL("../../lib/sequences/sequences.ts", import.meta.url), "utf8");
const sequenceActions = await readFile(new URL("../../app/actions/sequences.ts", import.meta.url), "utf8");
const sequenceScreen = await readFile(new URL("../../components/screens/sequences-screen.tsx", import.meta.url), "utf8");
const drawer = await readFile(new URL("../../components/ui/drawer.tsx", import.meta.url), "utf8");
const globalStyles = await readFile(new URL("../../app/globals.css", import.meta.url), "utf8");
const databaseReadme = await readFile(new URL("../README.md", import.meta.url), "utf8");
const implementationPlan = await readFile(new URL("../../docs/implementation-plan.md", import.meta.url), "utf8");

test("Phase 6 creates schedule and timing configuration, then simplifies templates into direct sequence variants", () => {
  assert.match(baseMigration, /add column throttle_max_sends_per_hour integer not null default 60/i);
  assert.match(baseMigration, /add column jitter_max_minutes integer not null default 0/i);
  assert.match(baseMigration, /campaign_sequence_schedules_sequence_key[\s\S]*unique \(workspace_id, campaign_id, sequence_id\)/i);
  assert.match(baseMigration, /add column subject text/i);
  assert.match(baseMigration, /add column body text/i);
  assert.match(migration, /drop function public\.campaign_sequence_create_step/i);
  assert.match(migration, /drop function public\.campaign_sequence_reorder_steps/i);
  assert.match(migration, /drop column sequence_step_id/i);
  assert.match(migration, /rename to campaign_sequence_variants/i);
  assert.match(migration, /campaign_sequence_variants_key_per_sequence[\s\S]*unique \(workspace_id, campaign_id, sequence_id, variant_key\)/i);
  assert.match(migration, /drop table public\.campaign_sequence_steps/i);
  assert.match(migration, /create function public\.campaign_sequence_save_variant/i);
  assert.match(migration, /jsonb_build_object\('subject', normalized_subject, 'body', normalized_body\)/i);
  assert.match(throttleRemovalMigration, /drop column throttle_max_sends_per_hour/i);
  assert.match(throttleRemovalMigration, /configured campaign mailboxes/i);
  assert.match(throttleRemovalMigration, /before insert or update of timezone, weekly_windows, jitter_max_minutes/i);
  assert.match(throttleRemovalMigration, /Temporary rolling-deployment compatibility wrapper/i);
  assert.match(finalPhaseMigration, /drop function public\.campaign_sequence_create\(uuid, text, text\)/i);
  assert.match(finalPhaseMigration, /drop function public\.campaign_sequence_update_configuration\(uuid, uuid, text, text, jsonb, integer\)/i);
  assert.match(finalPhaseMigration, /drop function public\.campaign_sequence_save_variant\(uuid, uuid, uuid, text, text, text\)/i);
  assert.match(finalPhaseMigration, /create function public\.campaign_sequence_create\([\s\S]*p_schedule_timezone text/i);
  assert.match(finalPhaseMigration, /generated_name := 'Step ' \|\| next_step_number::text/i);
  assert.match(finalPhaseMigration, /Campaign is active\. Pause it before adding a step/i);
  assert.match(finalPhaseMigration, /create function public\.campaign_sequence_delete/i);
  assert.match(finalPhaseMigration, /A step with enrollment history cannot be removed/i);
  assert.match(finalPhaseMigration, /remaining_step_labels_renumbered', true/i);
  assert.match(finalPhaseMigration, /create function public\.campaign_sequence_set_campaign_status/i);
  assert.match(finalPhaseMigration, /for sequence_record in[\s\S]*campaign_sequence_assert_activation_prerequisites[\s\S]*end loop;[\s\S]*if p_status = 'active'[\s\S]*update public\.campaign_sequences/i);
  assert.match(finalPhaseMigration, /Launch, pause, and resume must be applied to every non-archived step/i);
  assert.match(finalPhaseMigration, /campaign_sequence_variants_key_per_sequence[\s\S]*deferrable initially immediate/i);
  assert.match(finalPhaseMigration, /create function public\.campaign_sequence_variant_key_for_position/i);
  assert.match(finalPhaseMigration, /row_number\(\) over \(order by variant\.created_at asc, variant\.id asc\)/i);
  assert.match(finalPhaseMigration, /create function public\.campaign_sequence_save_variant\([\s\S]*p_subject text,[\s\S]*p_body text/i);
  assert.match(finalPhaseMigration, /count\(\*\)::integer \+ 1 into next_variant_position/i);
  assert.match(finalPhaseMigration, /remaining_variant_labels_renumbered', true/i);
  assert.doesNotMatch(finalPhaseMigration, /campaign_sequence_delete_with_history/i);
  assert.doesNotMatch(finalPhaseMigration, /rolling-deployment compatibility/i);
  assert.doesNotMatch(finalPhaseMigration, /p_variant_key/i);
  assert.match(variantRpcRepairMigration, /to_regprocedure\('public\.campaign_sequence_save_variant\(uuid,uuid,uuid,text,text\)'\) is not null/i);
  assert.match(variantRpcRepairMigration, /to_regprocedure\('public\.campaign_sequence_save_variant\(uuid,uuid,uuid,text,text,text\)'\) is null/i);
  assert.match(variantRpcRepairMigration, /create function public\.campaign_sequence_save_variant\([\s\S]*p_subject text,[\s\S]*p_body text/i);
  assert.match(variantRpcRepairMigration, /return public\.campaign_sequence_save_variant\([\s\S]*p_variant_id,[\s\S]*null,[\s\S]*p_subject,[\s\S]*p_body/i);
  assert.match(variantRpcRepairMigration, /grant execute on function public\.campaign_sequence_save_variant\(uuid, uuid, uuid, text, text\) to authenticated/i);
});

test("Phase 6 validates IANA timezones, non-overlapping windows, and direct-variant activation prerequisites transactionally", () => {
  assert.match(baseMigration, /create function public\.campaign_sequence_schedule_validate_configuration/i);
  assert.match(baseMigration, /pg_catalog\.pg_timezone_names/i);
  assert.match(baseMigration, /Weekly windows cannot overlap on the same weekday/i);
  assert.match(baseMigration, /with ordinality as window_entry\(value, ordinality\)/i);
  assert.doesNotMatch(baseMigration, /with ordinality as window\(value, ordinality\)/i);
  assert.match(migration, /for update;/i);
  assert.match(migration, /create or replace function public\.campaign_sequence_assert_activation_prerequisites/i);
  assert.match(migration, /Activation requires at least one weekly sending window/i);
  assert.match(migration, /Activation requires at least one complete template variant/i);
  assert.match(migration, /nullif\(btrim\(variant\.subject\), ''\) is not null[\s\S]*nullif\(btrim\(variant\.body\), ''\) is not null/i);
  assert.doesNotMatch(migration, /contiguous ordered steps/i);
  assert.match(baseMigration, /create function public\.campaign_sequence_set_status/i);
});

test("Phase 6 active sequences remain configuration-only and do not expose enrollment or dispatch behavior", () => {
  assert.match(baseMigration, /It deliberately creates no enrollment state machine, router, queue, scheduler, provider adapter, webhook, or send path/i);
  assert.match(baseMigration, /revoke all on function public\.campaign_sequence_enroll_lead\(uuid, uuid, uuid\) from authenticated/i);
  assert.match(baseMigration, /automation_configured', false/i);
  assert.match(migration, /without enrollment, send, or dispatch metrics/i);
  assert.doesNotMatch(baseMigration, /grant execute on function public\.campaign_sequence_enroll_lead[\s\S]*to authenticated/i);
  assert.match(sequenceScreen, /Automation not configured/i);
  assert.match(sequenceScreen, /cannot enroll contacts, route a mailbox, schedule work, or send email/i);
  assert.doesNotMatch(sequenceScreen, /Active enrollments/i);
});

test("Phase 6 derives sequence ownership from the signed-in workspace and validates untrusted form values", () => {
  assert.match(sequenceData, /getAuthorizedWorkspaceCampaignAccess/);
  assert.match(sequenceData, /campaign_sequence_update_configuration/);
  assert.match(sequenceData, /campaign_sequence_save_variant/);
  assert.match(sequenceData, /campaign_sequence_delete_variant/);
  assert.match(sequenceData, /campaign_sequence_delete/);
  assert.doesNotMatch(sequenceData, /campaign_sequence_delete_with_history/);
  assert.doesNotMatch(sequenceData, /throttleMaxSendsPerHour/);
  assert.match(sequenceData, /p_workspace_id: workspaceAccess\.workspaceId/);
  assert.match(sequenceActions, /sequenceConfigurationInput/);
  assert.match(sequenceActions, /validIanaTimezone/);
  assert.match(sequenceActions, /windowsOverlap/);
  assert.match(sequenceActions, /uuidPattern/);
  assert.match(sequenceActions, /revalidatePath\(actionPath\)/);
  assert.doesNotMatch(sequenceActions, /variantKeyPattern/);
  assert.doesNotMatch(sequenceActions, /formData\.get\("variantKey"\)/);
  assert.doesNotMatch(sequenceData, /p_variant_key/);
  assert.match(sequenceData, /Campaign launch requires every non-archived step to have a weekly window and at least one complete subject\/body template variant/i);
  assert.doesNotMatch(sequenceActions, /deleteSequenceWithHistoryAction/);
  assert.doesNotMatch(sequenceActions, /throttleMaxSendsPerHour/);
  assert.doesNotMatch(sequenceActions, /formData\.get\("name"\)/);
});

/** Guards data preservation while removing obsolete step-only configuration. */
test("Phase 6 migrates saved variants directly onto their sequence without showing or creating placeholder templates", () => {
  assert.match(migration, /row_number\(\) over \([\s\S]*partition by variant\.workspace_id, variant\.campaign_id, variant\.sequence_id, variant\.variant_key/i);
  assert.match(migration, /candidate_key := 'migrated-'/i);
  assert.match(migration, /create or replace function public\.campaign_sequence_create/i);
  assert.doesNotMatch(migration, /campaign_sequence_create_step\(p_workspace_id, new_sequence_id, 0\)/i);
  assert.match(migration, /create function public\.campaign_sequence_delete_variant/i);
  assert.match(migration, /delete from public\.campaign_sequence_variants/i);
  assert.match(migration, /grant execute on function public\.campaign_sequence_delete_variant\(uuid, uuid, uuid\) to authenticated/i);
  assert.match(sequenceScreen, /function SequenceVariantsDropdown/i);
  assert.match(sequenceScreen, /function SequenceTableRows/i);
  assert.match(sequenceScreen, /Show template variants/i);
  assert.match(sequenceScreen, /aria-expanded=\{variantsOpen\}/i);
  assert.match(sequenceScreen, /Add, edit, or remove variants here/i);
  assert.match(sequenceScreen, /sequence-variants-enter/i);
  assert.match(sequenceScreen, /sequence-variants-exit/i);
  assert.match(sequenceScreen, /variant="secondary">\{editing \? "Close" : "Edit"\}<\/Button>/i);
  assert.match(sequenceScreen, /variant="danger">Delete variant<\/Button>/i);
  assert.match(sequenceScreen, /aria-controls=\{editorId\} aria-expanded=\{editing\}/i);
  assert.match(sequenceScreen, /variant-editor-enter/i);
  assert.match(sequenceScreen, /function toggleVariants/i);
  assert.match(drawer, /drawer-panel-enter/i);
  assert.match(drawer, /drawer-panel-exit/i);
  assert.match(drawer, /onCloseComplete/i);
  assert.match(globalStyles, /@keyframes sequence-variants-enter/i);
  assert.match(globalStyles, /@keyframes sequence-variants-exit/i);
  assert.match(globalStyles, /@keyframes variant-editor-enter/i);
  assert.match(globalStyles, /@keyframes drawer-panel-enter/i);
  assert.match(globalStyles, /@keyframes drawer-panel-exit/i);
  assert.match(globalStyles, /prefers-reduced-motion: reduce[\s\S]*drawer-panel-enter[\s\S]*drawer-panel-exit[\s\S]*sequence-variants-enter[\s\S]*sequence-variants-exit[\s\S]*variant-editor-enter/i);
  assert.doesNotMatch(sequenceScreen, /function SequenceVariantsEditor/i);
  assert.match(sequenceScreen, /function AddVariantForm/i);
  assert.match(sequenceScreen, /Add template variant/i);
  assert.match(sequenceScreen, /<TableCell className="max-w-md text-\[var\(--ink-muted\)\]"><span className="block truncate" title=\{variant\.body\}>\{variant\.body\}/i);
  assert.doesNotMatch(sequenceScreen, /function templatePreview/i);
  assert.match(sequenceScreen, /Database-assigned labels stay with this step in creation order/i);
  assert.match(sequenceScreen, /variant\.variantKey\.toUpperCase\(\)/i);
  assert.doesNotMatch(sequenceScreen, /name="variantKey"/i);
  assert.match(sequenceScreen, /configured campaign mailboxes/i);
  assert.doesNotMatch(sequenceScreen, /Future maximum sends per hour/i);
  assert.match(sequenceScreen, /automatically named Step 1, Step 2, and so on/i);
  assert.doesNotMatch(sequenceScreen, /name="name"/i);
  assert.doesNotMatch(sequenceScreen, /Add step/i);
  assert.doesNotMatch(sequenceScreen, /Delay after previous step/i);
  assert.doesNotMatch(sequenceScreen, /function SequenceStep/i);
  assert.match(sequenceScreen, /function RemoveStepControl/);
  assert.match(sequenceScreen, /Remove \{sequence\.name\}\?/);
  assert.match(sequenceScreen, /A step with enrollment history cannot be removed/i);
  assert.doesNotMatch(sequenceScreen, /Remove step & history/i);
  assert.match(sequenceScreen, /Remaining generated Step N labels will be compacted/i);
  assert.match(sequenceActions, /Remaining generated step labels have been renumbered/i);
  assert.match(sequenceScreen, /function stepIsEditable/);
  assert.match(sequenceScreen, /const \[drawerClosing, setDrawerClosing\] = useState\(false\)/);
  assert.match(sequenceScreen, /const completeDrawerClose = useCallback/i);
  assert.match(sequenceScreen, /status === "draft" \|\| sequence\.status === "paused"/);
  assert.match(sequenceScreen, /label: "Launch campaign"/);
  assert.match(sequenceScreen, /label: "Pause campaign"/);
  assert.match(sequenceScreen, /label: "Resume campaign"/);
  assert.match(sequenceScreen, /value=\{action\.status\}/);
  assert.match(sequenceScreen, /function CampaignStatusControl/);
  assert.match(sequenceScreen, /function ArchiveStepControl/);
  assert.match(sequenceScreen, /Archive step/);
  assert.match(sequenceScreen, /all \$\{mutableStepCount\} non-archived steps/i);
  assert.match(sequenceScreen, /<PageHeader actions=\{canManageSequences && campaignAction/i);
  assert.match(sequenceScreen, /const campaignIsRunning = activeConfigurationCount > 0/);
  assert.match(sequenceScreen, /const canCreateStep = canManageSequences && !campaignIsRunning/);
  assert.match(sequenceScreen, /Pause the active campaign before adding another step/i);
  assert.match(sequenceData, /Pause the active campaign before adding a step/i);
  assert.match(sequenceData, /campaign_sequence_set_campaign_status/);
  assert.match(sequenceActions, /setCampaignLifecycleStatus/);
  assert.match(sequenceScreen, /mode: "remove"/);
  assert.match(sequenceScreen, /aria-label=\{`Remove \$\{sequence\.name\}`\}/);
  assert.match(sequenceScreen, /aria-label=\{`Configure \$\{sequence\.name\}`\}/);
});

test("Phase 6 documentation calls out the migration, no new variables, and the missing automation boundary", () => {
  assert.match(databaseReadme, /Phase 6 sequence configuration drafts/i);
  assert.match(databaseReadme, /20260903000600_phase_6_sequence_configuration_drafts\.sql/i);
  assert.match(databaseReadme, /20260909000100_phase_6_sequence_direct_variants\.sql/i);
  assert.match(databaseReadme, /20260909000200_phase_6_remove_sequence_throttle\.sql/i);
  assert.match(databaseReadme, /20260909000300_phase_6_final_sequence_configuration\.sql/i);
  assert.match(databaseReadme, /20260909000400_phase_6_variant_rpc_signature_repair\.sql/i);
  assert.match(implementationPlan, /20260909000300_phase_6_final_sequence_configuration\.sql/i);
  assert.match(implementationPlan, /20260909000400_phase_6_variant_rpc_signature_repair\.sql/i);
  assert.match(databaseReadme, /fresh or reset project database/i);
  assert.match(implementationPlan, /For a fresh or reset database/i);
  assert.doesNotMatch(databaseReadme, /20260909000400_phase_6_remove_numbered_step\.sql/i);
  assert.doesNotMatch(databaseReadme, /20260909000500_phase_6_temporary_step_history_cleanup\.sql/i);
  assert.doesNotMatch(databaseReadme, /20260909001000_phase_6_database_numbered_variant_labels\.sql/i);
  assert.match(databaseReadme, /no new environment variables/i);
  assert.match(implementationPlan, /Phase 6/i);
  assert.match(implementationPlan, /Automation is not configured/i);
});
